# Generated by Django 3.2.8 on 2021-10-27 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LotInv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_lid', models.CharField(max_length=8, verbose_name='lid')),
                ('c_site', models.IntegerField(verbose_name='site')),
                ('c_block', models.IntegerField(verbose_name='block')),
                ('c_lot', models.IntegerField(verbose_name='lot')),
                ('c_lot_area', models.IntegerField(verbose_name='lot_area')),
                ('c_price_sqm', models.IntegerField(verbose_name='price_sqm')),
                ('c_remarks', models.CharField(max_length=200, verbose_name='remarks')),
                ('c_status', models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('On Hold', 'On Hold'), ('Reserved', 'Reserved'), ('Packaged', 'Packaged')], max_length=50, null=True)),
                ('c_lot_type', models.CharField(choices=[('Regular Lot', 'Regular Lot'), ('Prime Lot', 'Prime Lot')], max_length=50, null=True)),
                ('c_title', models.CharField(choices=[('With Title', 'With Title'), ('Without Title', 'Without Title')], max_length=50, null=True)),
                ('c_lot_type_remarks', models.CharField(max_length=200, verbose_name='lot_type_remarks')),
                ('c_title_owner', models.CharField(max_length=50, verbose_name='title_owner')),
                ('c_previous_owner', models.CharField(max_length=50, verbose_name='previous_owner')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_acronym', models.CharField(max_length=10, verbose_name='acronym')),
                ('c_code', models.CharField(max_length=5, verbose_name='code')),
                ('c_name', models.CharField(max_length=100, verbose_name='name')),
                ('c_location', models.CharField(max_length=100, verbose_name='location')),
            ],
        ),
    ]
