# Generated by Django 3.2.8 on 2021-10-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot_inv', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotinv',
            name='c_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('On Hold', 'On Hold'), ('Reserved', 'Reserved'), ('Packaged', 'Packaged')], max_length=50, null=True),
        ),
    ]
