# Generated by Django 3.2.8 on 2021-10-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot_inv', '0002_alter_lotinv_c_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotinv',
            name='c_title',
            field=models.CharField(choices=[('With Title', 'With Title'), ('Without Title', 'Without Title')], max_length=50, null=True),
        ),
    ]
