# Generated by Django 3.2.8 on 2021-10-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot_inv', '0003_alter_lotinv_c_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotinv',
            name='c_lot_type',
            field=models.CharField(choices=[('Regular Lot', 'Regular Lot'), ('Prime Lot', 'Prime Lot')], max_length=50, null=True),
        ),
    ]
