# Generated by Django 3.2.8 on 2021-10-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot_inv', '0004_alter_lotinv_c_lot_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotinv',
            name='c_status',
            field=models.CharField(choices=[(133, 'GR-1B'), (141, 'GR-7E'), (150, 'RE-2'), (106, 'GIE'), (149, 'WGR'), (103, 'GR-1'), (105, 'GR-2'), (108, 'GR-2A'), (110, 'GR-1A'), (111, 'GR-3'), (113, 'GR-4'), (115, 'GR-5'), (114, 'DCH-1A'), (118, 'GR-5A'), (104, 'DCH-1'), (107, 'DCH-2A'), (109, 'DCH-2B'), (112, 'DCH-3'), (116, 'DCH-4'), (117, 'DCH-5'), (119, 'GR-6'), (137, 'DCH-2C'), (138, 'DCH-5A'), (120, 'GR-7'), (145, 'DCH-5B'), (147, 'DCH-5C'), (162, 'DCH-5D'), (192, 'DCH-AH'), (163, 'WGR-3'), (158, 'DCH-2D'), (165, 'GR-3B'), (121, 'GR-8'), (122, 'GR-9'), (124, 'GR-8A'), (125, 'GR-8B'), (126, 'GR-8C'), (127, 'GR-9A'), (128, 'GR-10'), (129, 'GR-8D'), (130, 'GR-7A'), (134, 'GR-1C'), (135, 'GR-7C'), (146, 'GR-7F'), (131, 'GR-8E'), (142, 'GR-5B'), (132, 'GR-7B'), (143, 'GR-6A'), (136, 'GR-4A'), (148, 'GR-6B'), (139, 'GR-3A'), (140, 'GR-7D'), (144, 'GR-5C'), (151, 'GR-5D'), (101, 'RE'), (193, 'GR-AH'), (190, 'RE-AH'), (194, 'MEAD-AH'), (156, 'WGR-2'), (155, 'GR-7G'), (153, 'GR-1D'), (154, 'GR-1E'), (160, 'GR-1F'), (159, 'GR-7H'), (102, 'CR'), (191, 'CR-AH'), (123, 'MEADOWS'), (164, 'MEADOWS-2'), (167, 'WGR-1A'), (171, 'GR-7I'), (173, 'GR-6C'), (174, 'WGR-4'), (175, 'GR-9B'), (176, 'WGR-2A'), (177, 'WGR-1B'), (181, 'WGR-2B'), (184, 'GR-6D'), (179, 'GR-6E'), (178, 'GR-8F'), (185, 'DCH-5E'), (157, 'CBP-2'), (161, 'CBP-1A'), (166, 'CBP-2A'), (168, 'CBP-3'), (169, 'CBP-4'), (170, 'CBP-2B'), (172, 'CBP-5'), (180, 'CBP-1B'), (182, 'CBP-3A'), (183, 'CBP-5A'), (186, 'CBP-3B'), (187, 'CBP-5B'), (152, 'CBP'), (188, 'GR-7J'), (189, 'CBP-3C'), (195, 'CBP-2C'), (196, 'CBP-3D')], max_length=50, null=True),
        ),
    ]
