# Generated by Django 3.2.8 on 2021-10-26 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lot_inv', '0005_alter_lotinv_c_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lotinv',
            name='c_site',
            field=models.IntegerField(choices=[(152, 'CBP'), (161, 'CBP-1A'), (180, 'CBP-1B'), (157, 'CBP-2'), (166, 'CBP-2A'), (170, 'CBP-2B'), (195, 'CBP-2C'), (168, 'CBP-3'), (182, 'CBP-3A'), (186, 'CBP-3B'), (189, 'CBP-3C'), (196, 'CBP-3D'), (169, 'CBP-4'), (172, 'CBP-5'), (183, 'CBP-5A'), (187, 'CBP-5B'), (102, 'CR'), (191, 'CR-AH'), (104, 'DCH-1'), (114, 'DCH-1A'), (107, 'DCH-2A'), (109, 'DCH-2B'), (137, 'DCH-2C'), (158, 'DCH-2D'), (112, 'DCH-3'), (116, 'DCH-4'), (117, 'DCH-5'), (138, 'DCH-5A'), (145, 'DCH-5B'), (147, 'DCH-5C'), (162, 'DCH-5D'), (185, 'DCH-5E'), (192, 'DCH-AH'), (106, 'GIE'), (103, 'GR-1'), (128, 'GR-10'), (110, 'GR-1A'), (133, 'GR-1B'), (134, 'GR-1C'), (153, 'GR-1D'), (154, 'GR-1E'), (160, 'GR-1F'), (105, 'GR-2'), (108, 'GR-2A'), (111, 'GR-3'), (139, 'GR-3A'), (165, 'GR-3B'), (113, 'GR-4'), (136, 'GR-4A'), (115, 'GR-5'), (118, 'GR-5A'), (142, 'GR-5B'), (144, 'GR-5C'), (151, 'GR-5D'), (119, 'GR-6'), (143, 'GR-6A'), (148, 'GR-6B'), (173, 'GR-6C'), (184, 'GR-6D'), (179, 'GR-6E'), (120, 'GR-7'), (130, 'GR-7A'), (132, 'GR-7B'), (135, 'GR-7C'), (140, 'GR-7D'), (141, 'GR-7E'), (146, 'GR-7F'), (155, 'GR-7G'), (159, 'GR-7H'), (171, 'GR-7I'), (188, 'GR-7J'), (121, 'GR-8'), (124, 'GR-8A'), (125, 'GR-8B'), (126, 'GR-8C'), (129, 'GR-8D'), (131, 'GR-8E'), (178, 'GR-8F'), (122, 'GR-9'), (127, 'GR-9A'), (175, 'GR-9B'), (193, 'GR-AH'), (194, 'MEAD-AH'), (123, 'MEADOWS'), (164, 'MEADOWS-2'), (101, 'RE'), (150, 'RE-2'), (190, 'RE-AH'), (149, 'WGR'), (167, 'WGR-1A'), (177, 'WGR-1B'), (156, 'WGR-2'), (176, 'WGR-2A'), (181, 'WGR-2B'), (163, 'WGR-3'), (174, 'WGR-4')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lotinv',
            name='c_status',
            field=models.CharField(choices=[('Available', 'Available'), ('Sold', 'Sold'), ('On Hold', 'On Hold'), ('Reserved', 'Reserved'), ('Packaged', 'Packaged')], max_length=50, null=True),
        ),
    ]
